### ISSUE TITLE
没法用

### ISSUE THREAD

**Issue by kanxue660** [antiwar3/py#1]
虚拟机里面，win7 x64企业版，启动不久，估计有10秒，就没法操作了，程序界面卡死，点击没反应，

**Comment by antiwar3** [comment]
你好 请问是企业版的7600 还是7601

**Comment by kanxue660** [comment]
7601

**Comment by antiwar3** [comment]
试试最新的好了不

**Comment by kanxue660** [comment]
不行，还是那样，用一会就没反应了;操作系统账号为普通管理员，如果右键“以管理员运行”，界面启动就死了，还不如普通的双击运行；旗舰版的也不行，启动就没反应了

**Comment by kanxue660** [comment]
本机是server2019，运行欢快，估计程序被虚拟机影响了

**Comment by antiwar3** [comment]
那不知道为啥了 我在msdn下载的WIN7旗舰版7600 7601能正常跑起来

**Comment by kanxue660** [comment]
> 那不知道为啥了 我在msdn下载的WIN7旗舰版7600 7601能正常跑起来

也是在虚拟机里面跑的么？虚拟机用的是vmware 还是 virtualbox?

**Comment by antiwar3** [comment]
我虚拟机和实体机都跑了，虚拟机是VMWARE
WIN7旗舰版SP1镜像
ed2k://|file|cn_windows_7_ultimate_with_sp1_x64_dvd_u_677408.iso|3420557312|B58548681854236C7939003B583A8078|/

**Comment by kanxue660** [comment]
vmware里面用win10测试了下，运行正常；不确定是否vb的问题，希望有其他人能反馈下virtualbox的运行情况
