### ISSUE TITLE
Pyark for Windows 11 Version 21H2

### ISSUE THREAD

**Issue by J4yRich** [antiwar3/py#11]
Hello,

Can you update the version for the software compatible with Windows 11 version 21H2?
I found it to work on Windows 11 but the features don't seem to work...

**Comment by BrianBec21** [comment]
in fact if you can because in a version of Windows 10 Home Insider Preview that is the 22394.rs_onecore_csd.210528-1535 the problems in compatibility mode with Windows 8 are fixed or if there is a possibility with Windows 10

**Comment by BrianBec21** [comment]
in fact if you can because in a version of Windows 10 Home Insider Preview that is the 22394.rs_onecore_csd.210528-1535 the problems in compatibility mode with Windows 8 are fixed or if there is a possibility with Windows 10
