### ISSUE TITLE
added Supporter OS Patch Pls

### ISSUE THREAD

**Issue by kakaon1** [antiwar3/py#12]
added Supporter OS

Windows10 LTSC 2021
Windows10 21H2
Windows11 21H2

Pls!!!

Program Running

Windows 10 21H2 Program Load Not Error 

Not GUI Load

Not Message

Program Problem Fixed Pls!

Program update Patch Expect.

**Comment by antiwar3** [comment]
Windows10 LTSC 2021
Windows10 21H2
Windows11 21H2
Already supported
