### ISSUE TITLE
内核钩子->内核钩子蓝屏

### ISSUE THREAD

**Issue by 0x391F** [antiwar3/py#14]
系统 Windows 10 Enterprise LTSC 2021 x64 (21H2)

**Comment by 0x391F** [comment]
虚拟机 Windows 10 Enterprise LTSC 2019 x64 (1809) 似乎没有问题

**Comment by 0x391F** [comment]
错误代码：NONPAGED_AREA

**Comment by antiwar3** [comment]
因为ms一堆动态patch比如CFG等，这个功能废了，内核钩子的bug无视把

**Comment by antiwar3** [comment]
内核钩子扫描无意义了，因为ms多了很多动态patch&nbsp;


antiwar3
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年8月11日(星期四) 上午9:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; 
主题: Re: [antiwar3/py] 内核钩子-&gt;内核钩子蓝屏 (Issue #14)





 
错误代码：NONPAGED_AREA
