### ISSUE TITLE
Windows 10 x64 1909 18363.1557 loaddriver failed

### ISSUE THREAD

**Issue by HackerBBW** [antiwar3/py#27]
![1685726145314](https://github.com/antiwar3/py/assets/43372656/73b713ce-16c9-4ba1-8420-ef16e644b47d)

**Comment by antiwar3** [comment]
是签名问题
C:\Windows\System32\drivers\PYArkSafe.sys
找到这个文件 然后自己签名放到exe同级目录即可，改名叫PYarkSafe64.sys
