### ISSUE TITLE
Load Driver Error on Windows Server 2012 R2

### ISSUE THREAD

**Issue by Slackerok** [antiwar3/py#3]
Hi. Please fix the error of Driver on OS: Windows Server 2012 R2
I check right now, don't load the driver.
After this I try to start on Windows 10, and it crashed my PC. The computer just hangs and does not react in any way. Had to reboot..
The software is still very raw and is not suitable for mass work. You need to refine its stability.

**Comment by antiwar3** [comment]
hello friend，Windows server version not supported，on windows 10 you can update your system to version 1909



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Slackerok"<notifications@github.com&gt;; 
发送时间: 2020年6月10日(星期三) 上午9:14
收件人: "antiwar3/py"<py@noreply.github.com&gt;; 
抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 
主题: [antiwar3/py] Load Driver Error on Windows Server 2012 R2 (#3)





 
Hi. Please fix the error of Driver on OS: Windows Server 2012 R2
 I check right now, don't load the driver.
 After this I try to start on Windows 10, and it crashed my PC. The computer just hangs and does not react in any way. Had to reboot..
 The software is still very raw and is not suitable for mass work. You need to refine its stability.
