### ISSUE TITLE
高分屏显示异常

### ISSUE THREAD

**Issue by Greyh4t** [antiwar3/py#4]
屏幕分辨率高的电脑上显示异常，进程标签可以调节显示高度，其他标签无法调节，同时无法记录，下次打开还是一样

![微信截图_20200723105314](https://user-images.githubusercontent.com/8017380/88248183-deb7b000-ccd2-11ea-966f-b75b0645cbe3.png)

**Comment by antiwar3** [comment]
下版本修复

**Comment by antiwar3** [comment]
已修复

**Comment by Greyh4t** [comment]
没问题了 给力
