### ISSUE TITLE
loaddriver failled bug on Window 10

### ISSUE THREAD

**Issue by seiyashun** [antiwar3/py#8]
I've got a issue with loaddriver failled on Window 10
![image](https://user-images.githubusercontent.com/15777662/126733822-f45308f3-53f0-46f5-8db5-2dc20ec7e3a2.png)
![image](https://user-images.githubusercontent.com/15777662/126733878-f97be88d-93a7-4e37-a2fd-1e57ef4f2658.png)
Please help me to check it. Thank you

**Comment by antiwar3** [comment]
fix it. download it again

**Comment by seiyashun** [comment]
Fixed, thank for your supporting
